<?php
date_default_timezone_set('America/Chicago');
include 'cheatsheat.php';
require_once 'login.php';
$db_server = new mysqli("localhost", "root", "root", "schedule");
if ($db_server->connect_errno) {
    echo "Failed to connect to MySQL: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
}

echo "<link rel='stylesheet' type='text/css' href='style.css'>
    <title> HH Admin Page </title>
    <div id = 'header'> <a href='schoollogo.jpeg'> </a>hhcycly  </div>  ";


$today = date('Y-m-d');

//turns days off
echo "Add day off: <form action='post.php' method='post'><input type='text' name='dayoff' /><input type='submit' /> </form> ";
echo "Change a date to a short class day: <form action='post.php' method='post'><input type='text' name='special' /><input type='submit' /> </form> ";



function table_month_gen($month) {
    $db_server = mysqli_connect("localhost", "root", "root", "schedule");
    if (mysqli_connect_errno()) {
    printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
    }
    //this will, in turn, call table_week_gen for each week necessary
    
    $table = "<table  ";
    $i = date('Y-m-d', strtotime($month));
    $monthvalueofstart = date('m', strtotime($i));
    //go from date to next monday
    while ($monthvalueofstart = '01'):
        $newweek = table_week_gen($i);
        $table .= $newweek;
        $i = date('Y-m-d', strtotime("next monday", strtotime($startvalue)));
    endwhile;    
    $table .= "  </table>";
    echo $table;
    
    
    
}


function table_week_gen($firstdayofweek) {
    $db_server = mysqli_connect("localhost", "root", "root", "schedule");
    if (mysqli_connect_errno()) {
    printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
    }
    
    //what this WILL do is put together the cells generated by the individual day funtion
    $x = 0;
    $table_row = "<tr>   ";
    $queryformdate = date('Y-m-d', strtotime($firstdayofweek));
    mylog("$firstdayofweek formatted for the database is $queryformdate");
    $daynumeric = date('N', strtotime("+ $x days", strtotime($firstdayofweek)));
    mylog("starting with daynumeric=$daynumeric");
    for($i = 1; $i <= $daynumeric - 1; $i++) {
        $table_row .= " <td> &nbsp </td>";
    }
    while ($daynumeric <= 5):
        $nextday = date('Y-m-d', strtotime("+ $x days", strtotime($firstdayofweek)));
        mylog("working on the day  $nextday");
        $cellforthisday = table_day_gen($nextday);
        $table_row .= $cellforthisday;
        $x = $x + 1;
        $daynumeric = date('N', strtotime("+ $x days", strtotime($firstdayofweek)));

        //echo "<table> <tr> $cellforthisday </tr> </table>";
    endwhile;
    $table_row .= " </tr>";
    return $table_row;
    
}

function table_day_gen($date) {
    mylog("table day gen was called for $date");
    //This pulls the info for $date to display inside the table
    $db_server = mysqli_connect("localhost", "root", "root", "schedule");
    if (mysqli_connect_errno()) {
    printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
    }
    //Queries
    $cycledayvaluequery = "SELECT cycleday FROM days WHERE daate = '$date';";
    $activevaluequery = "SELECT active FROM days WHERE daate = '$date';";
    $specialquery = "SELECT specialsched FROM days WHERE daate = '$date';";
    
    mylog("Queries are: $cycledayvaluequery, $activevaluequery, $specialquery");
    
    //Running Queries
    //results will be: $active_result, $cyc_result, and $spec_result
    
    //cycle query
    $result_of_cycle_query = mysqli_query($db_server, $cycledayvaluequery);
    //mylog('ran the inactive day query');
    if ($result_of_cycle_query->connect_errno) {
    echo "Failed to connect to MySQL: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
    //And when pulling a row, use this part
    }
    
    $cycrow = mysqli_fetch_array($result_of_cycle_query, MYSQLI_ASSOC);
    $cyc_result = $cycrow["cycleday"];
    mylog("cyc result for $date returned $cyc_result");
    
    
    //active query
    $result_of_active_query = mysqli_query($db_server, $activevaluequery);
    //mylog('ran the inactive day query');
    if ($result_of_active_query->connect_errno) {
    echo "Failed to connect to MySQL: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
    //And when pulling a row, use this part
    }
    
    $activerow = mysqli_fetch_array($result_of_active_query, MYSQLI_ASSOC);
    $active_result = $activerow["active"];
    mylog("active result for $date returned $active_result");
    
    
    //special query
    $result_of_spec_query = mysqli_query($db_server, $specialquery);
    //mylog('ran the inactive day query');
    if ($result_of_spec_query->connect_errno) {
    echo "Failed to connect to MySQL: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
    //And when pulling a row, use this part
    }
    
    $specrow = mysqli_fetch_array($result_of_spec_query, MYSQLI_ASSOC);
    $spec_result = $specrow["specialsched"];
    mylog("spec result for $date returned $active_result");
    
    
    
    //creating the cell:
    $cellforthisday = "<td> $date  $active_result </br> $cyc_result  $spec_result </td>";
    //$cellforthisday = ${'cellfor'.$date};
    return $cellforthisday;
    
}





//table_day_gen($today);
table_month_gen("January 1");































mysqli_close();

?>
