<?php
date_default_timezone_set('America/Chicago');
include 'cheatsheat.php';
require_once 'login.php';
$db_server = new mysqli("localhost", "root", "root", "schedule");
if ($db_server->connect_errno) {
    echo "Failed to connect to MySQL: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
}

echo "<link rel='stylesheet' type='text/css' href='style.css'>
    <title> HH Admin Page </title>
    <div id = 'header'> <a href='schoollogo.jpeg'> </a>hhcyclr  </div>  ";


$today = date('Y-m-d');

//turns days off
echo "Add day off: <form action='post.php' method='post'><input type='text' name='dayoff' /><input type='submit' /> </form> ";
echo "Change a date to a short class day: <form action='post.php' method='post'><input type='text' name='special' /><input type='submit' /> </form> ";



function table_month_gen($month) {
    $db_server = mysqli_connect("localhost", "root", "root", "schedule");
    if (mysqli_connect_errno()) {
    printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
    }
    
    //this will, in turn, call table_week_gen for each week necessary
}


function table_week_gen(/*some date something idk yet??*/) {
    $db_server = mysqli_connect("localhost", "root", "root", "schedule");
    if (mysqli_connect_errno()) {
    printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
    }
    
    //what this WILL do is put together the cells generated by the individual day funtion
    
}

function table_day_gen($date) {
    $db_server = mysqli_connect("localhost", "root", "root", "schedule");
    if (mysqli_connect_errno()) {
    printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
    }
    
    $cycledayvaluequery = "SELECT cycleday FROM days WHERE daate = '$date';";
    $activevaluequery = "SELECT active FROM days WHERE daate = '$date';";
    $specialquery = "SELECT active FROM days WHERE daate = '$date';";
    
}






































mysqli_close($db_server);

?>
